image: condaforge/mambaforge:latest

stages:
  - test

variables:
  PYVERSION: "3.8"
  RSMVERSION: "11.3.0"
  BINPATH: "/root/rsmenv/bin"
  TESTDIR: "/root/rsmcode/tests"

# set up the basic job to run only for pull requests
.runtests:
  only:
    - external_pull_requests
  before_script:
    - mkdir /root/rsmcode
    - cd /root/rsmcode
    - git init
    - git remote add -f origin https://github.com/EducationalTestingService/rsmtool.git
    - git config core.sparsecheckout true
    - echo "tests/*" > .git/info/sparse-checkout
    - git pull --depth=1 origin main
    - mamba create --prefix /root/rsmenv -c conda-forge -c ets python=${PYVERSION} rsmtool=${RSMVERSION} nose2 --yes

  script:
    - "/root/rsmenv/bin/nose2 --quiet -s tests ${TESTFILES}"

# first set of test files
testset1:
  extends: ".runtests"
  variables:
    TESTFILES: "test_experiment_rsmtool_1"
  stage: "test"

# second set of test files
testset2:
  extends: ".runtests"
  variables:
    TESTFILES: "test_comparer test_configuration_parser test_experiment_rsmtool_2"
  stage: "test"

# third set of test files
testset3:
  extends: ".runtests"
  variables:
    TESTFILES: "test_analyzer test_experiment_rsmeval test_fairness_utils test_utils_prmse test_container test_test_utils test_cli"
  stage: "test"

# fourth set of test files
testset4:
  extends: ".runtests"
  variables:
    TESTFILES: "test_experiment_rsmcompare test_experiment_rsmsummarize test_modeler test_preprocessor test_writer test_experiment_rsmtool_3"
  stage: "test"

# fifth set of test files
testset5:
  extends: ".runtests"
  variables:
    TESTFILES: "test_experiment_rsmpredict test_reader test_reporter test_transformer test_utils test_experiment_rsmtool_4"
  stage: "test"

# sixth set of test files
testset6:
  extends: ".runtests"
  variables:
    TESTFILES: "test_experiment_rsmxval test_experiment_rsmexplain test_explanation_utils test_wandb"
  stage: "test"
