build: false

environment:
  RSMVERSION: 5.7

matrix:
  - PYTHON_VERSION: 3.6
    MINICONDA: C:\Miniconda3

platform:
  - x64

init:
  - "ECHO %PYTHON_VERSION% %MINICONDA%"

install:
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - "conda create -y -n rsmenv -c defaults -c conda-forge -c desilinguist python=%PYTHON_VERSION% rsmtool=%RSMVERSION%"
  - git clone https://github.com/EducationalTestingService/rsmtool.git c:\rsmcode

test_script:
  - activate rsmenv
  - nosetests -v c:\rsmcode\tests
