# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

variables:
  MPLBACKEND: Agg
  RSMVERSION: 7.1.0
  TESTDIR: 

trigger: none
pr:
- master

jobs:

- job: 'RSMToolTests'
  pool:
    vmImage: 'windows-latest'
  strategy:
    parallel: 5

  steps:
  - powershell: Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
    displayName: Add conda to PATH

  - script: |
      git clone https://github.com/EducationalTestingService/rsmtool.git rsmcode
    displayName: "Clone RSMTool repository"

  - script: |
      conda update --quiet --yes conda
      conda info -a
    displayName: "Update conda"

  - script: |
      conda create --name rsmdev --yes --quiet -c conda-forge -c ets python=%PYTHON_VERSION% rsmtool=%RSMVERSION%
      conda init cmd.exe
    displayName: 'Install RSMTool Package & Dependencies'

  - powershell: ./DistributeTests.ps1 
    displayName: 'PowerShell Script to distribute tests'

  - script: |
      echo $(pytestfiles)
      CALL activate rsmdev
      chdir $(Build.SourcesDirectory)\rsmcode
      nosetests --with-xunit $(pytestfiles)
    displayName: 'Run tests'

  - task: PublishTestResults@2
    displayName: 'Publish Test Results'
    inputs:
      testResultsFiles: 'nosetests.xml'
      testRunTitle: 'RSMTool tests'
    condition: succeededOrFailed()
