# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

variables:
  MPLBACKEND: Agg
  RSMVERSION: 7.0.0
  TESTDIR: $(Build.SourcesDirectory)\rsmcode\tests

trigger: none
pr:
- master

jobs:

- job: 'RSMToolTests'
  pool:
    vmImage: 'windows-latest'

  steps:
  - powershell: Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
    displayName: Add conda to PATH

  - script: |
      git clone https://github.com/EducationalTestingService/rsmtool.git rsmcode
    displayName: "Clone RSMTool repository"

  - script: |
      conda update --quiet --yes conda
      conda info -a
    displayName: "Update conda"

  - script: |
      conda create --name rsmdev --yes --quiet -c conda-forge -c desilinguist python=%PYTHON_VERSION% rsmtool=%RSMVERSION%
      conda init cmd.exe
    displayName: 'Install RSMTool Package & Dependencies'

  - script: |
      CALL activate rsmdev
      echo $(TESTDIR)
      nosetests $(Build.SourcesDirectory)\rsmcode\tests
    displayName: 'Run tests'
